### ISSUE TITLE
Update Syllabus for R lesson

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/2020-09-21-SWC-Gapminder#3]
Syllabus for R session is based on different lesson. It has to be updated with the content of [gapminder lesson](http://swcarpentry.github.io/r-novice-gapminder/). The teaching of the whole lesson takes 12 hours, so only part of it will be taught in this workshop.

**Comment by PabRod** [comment]
Do we already know which parts are we dropping and which ones are we keeping?

**Comment by mkuzak** [comment]
No, it's up to you, but I'm happy to discuss this with you if you want.

**Comment by PabRod** [comment]
Ok. It will take me a couple of days. I want to go through all the content first.

**Comment by mkuzak** [comment]
@PabRod I think now you have all the data to update the syllabus

**Comment by PabRod** [comment]
I think we can considered this closed :)
