### ISSUE TITLE
Update workshop schedule

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/2020-09-21-SWC-Gapminder#8]
Update in a way that there are two 15 minute breaks each day.

**Comment by PabRod** [comment]
I propose the breaks to be:

- 10:15 to 10:30
- 11:30 to 11:45

This way the day is divided into three sessions of 1:15 (first and last) and 1:00 (intermediate).

Is this ok, @mkuzak, @JensWehner?

**Comment by mkuzak** [comment]
Looks Good to Me :)
